from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = PROJECT_ROOT/"checkpoints"
OUTPUT_DIR.mkdir(exist_ok=True)
DATASET_PATH = "dataset"

SEED = 42

DATASET_NAME = "Helsinki-NLP/opus-100"
LANGUAGE_PAIR = "en-uk"

SOURCE_LANGUAGE = "en"
TARGET_LANGUAGE = "uk"

SOURCE_LANGUAGE_MBART = "en_XX"
TARGET_LANGUAGE_MBART = "uk_UA"

TRAIN_SAMPLES = 20000
VALIDATION_SAMPLES = 2000
TEST_SAMPLES = 2000

#MODEL_NAME = "google/mt5-base"
MODEL_NAME = "facebook/mbart-large-50"
MAX_LENGTH = 64
#OPTIMIZER = "adafactor"
OPTIMIZER = "adamw_torch"

NUM_EPOCHS = 5
LEARNING_RATE = 6e-5
TRAIN_BATCH_SIZE = 16
EVAL_BATCH_SIZE = 32
GRADIENT_ACCUMULATION_STEPS = 1
FP16 = True
GRADIENT_CHECKPOINTING = False
SAVE_STRATEGY = "epoch"
EVAL_STRATEGY = "epoch"
NUM_BEAMS = 4
WARMUP_STEPS = 20000

LOGGING_STEPS = 500

USE_SUBSET = True

BLEU_ENABLED = True
CHRF_ENABLED = True
COMET_ENABLED = False
COMET_MODEL = "Unbabel/wmt22-comet-da"

FILTER_LANGUAGE = True
LANG_CONFIDENCE_THRESHOLD = 0.7